[workspace]
members = [
    "programs/identity-challenge"
]
types = "packages/client/idl/src"

[features]
seeds = false
skip-lint = false

[programs.localnet]
identity_challenge = "chahabA9kRqd7kfdHsxSHTvPgwtfYRChf7u2vZtkDYS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./packages/tests/fixtures/A2oYuurjzc8ACwQQN56SBLv1kUmYJJTBjwMNWVNgVaT3.json"

[[test.genesis]]
address = "hhctGcofukzbGyYDKBnh99JA93UXjDoirvTaJwBedXP"
program = "packages/tests/fixtures/cryptid-hh_0.3.0-alpha.11.so"

[[test.genesis]]
address = "midb3GKX7wF1minPXeDKqGRKCK9NeR8ns9V8BQUMJDr"
program = "packages/tests/fixtures/check_did_0.3.0-alpha.11.so"

[[test.genesis]]
address = "didso1Dpqpm4CsiCjzP766BGY89CAdD6ZBL68cRhFPc"
program = "packages/tests/fixtures/sol_did_3.1.1.so"

[[test.genesis]]
address = "gate2TBGydKNyMNUqz64s8bz4uaWS9PNreMbmAjb1Ft"
program = "packages/tests/fixtures/solana_anchor_gateway.so"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 packages/tests/src/**/*.ts"
